// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1LYmO2FgBOrnLeP41Y8S5QLQ8NGvSgz8',
    appId: '1:803413626236:web:ae486f2c0d0510e7f5a8f9',
    messagingSenderId: '803413626236',
    projectId: 'baby-shop-8801b',
    authDomain: 'baby-shop-8801b.firebaseapp.com',
    storageBucket: 'baby-shop-8801b.firebasestorage.app',
    measurementId: 'G-Y26RKHBHZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy4o5v0LmpLQuJKAzU0LBLgicY6NOLT4s',
    appId: '1:803413626236:android:0c77db2353cdcd06f5a8f9',
    messagingSenderId: '803413626236',
    projectId: 'baby-shop-8801b',
    storageBucket: 'baby-shop-8801b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_V_nAXguH8PR9iK3enMqrlvvcFXa7T74',
    appId: '1:803413626236:ios:dbd5a88a8d0f4dfef5a8f9',
    messagingSenderId: '803413626236',
    projectId: 'baby-shop-8801b',
    storageBucket: 'baby-shop-8801b.firebasestorage.app',
    iosBundleId: 'com.example.babyShop',
  );
}
